Adde Vue app to display current date
js-tasks-ru/vue-20240924_stlthwl pull request #2
Opened 2024-10-28 15:07 UTC by stlthwl

- Created App component that uses setup method to get current date
- Date is displayed in "Today DATE" format using localization
- Used template to render date

2024-10-28 15:07 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-28 19:09 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-28 19:49 UTC, stlthwl commented
task#2 is done

2024-10-29 10:55 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-29 14:18 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-29 15:49 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-30 05:55 UTC, stlthwl commented
@ShGKme, есть замечания по выполнению?

2024-10-31 10:14 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-11-02 10:42 UTC, stlthwl commented
> Решение было обновлено, посмотрим что скажет @ShGKme

Обратную связь по решению можно получить?

2024-11-25 22:47 UTC, ShGKme requested changes
Добрый вечер. Понимаю, что может быть тяжело вносить правки после большого перерыва, но требуется исправления по некоторым задачам.

2024-11-25 22:47 UTC, ShGKme commented on 01-basics/20-weather/WeatherApp.js
> +          :class="['weather-card', isNight(item.current.sunrise, item.current.sunset, item.current.dt) ? 'weather-card--night' : '']">
Статические классы, которые всегда есть у элемента, можно описывать явно в шаблоне через обычный атрибут `class="weather-card"`. Так будет видно и основные классы верстки, и какие классы определяются динамически.

2024-11-25 22:47 UTC, ShGKme commented on 01-basics/20-weather/WeatherApp.js
> +  }
Здесь смешивается описание методов из Options API и описание компонента на Composition API. 

Хотя это технически работают, такое смешивание применяют только при миграции с Options API на Composition API, либо при использовании composables в Options API

2024-11-25 22:47 UTC, ShGKme commented on 01-basics/20-weather/WeatherApp.js
> +          :class="['weather-card', isNight(item.current.sunrise, item.current.sunset, item.current.dt) ? 'weather-card--night' : '']">
В том же месте, во Vue, когда требуется добавить класс по условию, принято использовать синтаксис привязки класса объектом. Объект явно описывает, какой класс по какому выражению требуется добавлять.

https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects 

Так явно видно, от чего зависит наличие каждого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы. 

И не требуется делать `else` с пустой строкой в тернарном операторе.

2024-11-25 22:47 UTC, ShGKme commented on 02-basics-2/20-broken-map/MapApp.js
> +      position: 'absolute',
`position: 'absolute'` уже есть в стилях и он статичный, его можно не добавлять через JS

2024-11-25 22:47 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +      <input type="number" aria-label="Second operand" v-model="operand2" @input="calculate" />
Здесь `result` обновляется вручную по событиям в приложении. События (действия пользователя) - лишь один из интерфейсов изменения состояния приложения. Основная идея Vue (и других фреймворков) в работе через состояние. Так не нужно будет следить за каждым местом на UI.

Причиной вычисления `result` должно быть изменение его зависимостей - операндов и оператора. Лучше всего для этого описать `result` как `computed`.

2024-11-25 22:47 UTC, ShGKme commented on 02-basics-2/40-marked-emails/MarkedEmailsApp.js
> +    })
На вебинаре мы использовали вычисляемое свойство для подготовки **отфильтрованных** данных и дальнейшего вывода отфильтрованного списка. Но здесь - другая задача. Здесь требуется вывести все данные, но некоторые элементы - **отметить** маркировкой.

В результате в текущем решении вычисляемое свойство не помогает выводить почты, а напротив, даже усложняет и замедляет вывод. При изменении фильтра:

1. Сначала перебираются циклом (`filter`) все почты для создания отфильтрованного списка (то есть каждая почта уже проверена).
2. Затем почты перебираются циклом (`v-for`) уже в шаблоне при рендеринге
3. И во время рендеринга каждой почты - опять перебирается циклом (`includes`) массив уже проверенных на п.1 почт. Чтобы узнать как прошла проверка почты ранее.

Требуется подумать, как сделать такое вычисляемое свойство, которое помогает решать задачу вывода маркированных почт.

Например, можно на основе исходного массива строк с почтами вернуть новый массив, где каждый элемент - объект. В объект уже можно положить как исходную почту, так и флаг о маркировке.

Тогда за один проход данные будут полностью готовы к выводу, и не потребуется опять перебирать данные во время вывода.

2024-11-25 22:47 UTC, ShGKme commented on 02-basics-2/40-marked-emails/MarkedEmailsApp.js
> +          :class="{ marked: search && email.toLowerCase().includes(search.toLowerCase()) }"
Напомню, что, хотя это не запрещено, лучше избегать вызова методов в шаблоне. Это делает его менее декларативным, и заставляет беспокоиться о его производительности или наличию у него побочных эффектов.

Особенно если они не простые утилиты, а методы обработки данных с перебором данных.

Для практики работы с Vue, здесь требуется подготовить данные к рендеру так, чтобы при выводе уже было известно, выводить ли текущий email промаркированным, или нет.

2024-12-10 09:22 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-10 10:11 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-12-10 10:27 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-12-10 11:30 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-12-10 14:59 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-12-10 18:28 UTC, ShGKme approved these changes
Все задачи приняты

2024-12-10 18:30 UTC, merged